apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3  # Runs 3 instances of the app for load balancing
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: flask-app
        image: rashmi2004/url-shortener:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: url-shortener-config  # ConfigMap name
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6379"

