apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80
      targetPort: 5000  # Flask app runs on 5000
  type: NodePort  # Use NodePort if on Minikube
